### ISSUE TITLE
jump to most expensive call

### ISSUE THREAD

**Issue by skliche** [skliche/request-metrics-analyzer-next#10] opened 2015-07-25 20:04 UTC
As a user
I want to be able to jump to the most expensive call in the use case tree view

**Comment by Florian-W** [comment] 2015-11-09 10:20
"Jump to most expensive call" means to jump to the most time expensive subtransaction in the "Transaction Drilldown" table, collapse all its children and highlight or select it. The user should be able to do this by clicking a button of a JToolBar above the table. It should only be enabled if a Business Transaction in the upper frame is selected. 
The program must compare the elapsed time of the parent node and its child nodes. We have the most expensive subtransaction where the biggest difference between the parent and one of its child nodes is. An algorithm will do the processing and return as result the most expensive subtransaction.

---

The UI with the toolbar and the button will look like this:
![wireframe 3](https://cloud.githubusercontent.com/assets/13657128/11030868/09a41eea-86d1-11e5-96ea-7397964bc7f5.jpg)

**Comment by Florian-W** [comment] 2015-11-10 13:53
A **recursive algorithm** should go through our tree-like data structure and **calculate the effective execution time** that was spent in a subtransaction. 
Going more into detail, the elapsed time of a node without children is also its execution time. For a parent node, the execution time is the difference of its elapsed time and the accumulated execution time of all its children. 
Therefore, the algorithm has to check whether the regarded node is a parent node and has children. If it has, these children must also be checked if they are parent nodes - so the algorithm is executed, until it reaches the last child nodes. It then runs "backwards" (from the child nodes over the parent nodes to the root case), calculating the execution time of all nodes.
To find the **most expensive subtransaction**, we save the longest execution time we found so far and overwrite it with the most recently calculated execution time if it exceeds the saved value. 

---

The algorithm will likely be structured as the following:
(1) Node → find children
                a) has no children → NodeExecutionTime = NodeElapsedTime
                totalExecutionTimeChildren += NodeExecutionTime
                b) has children → for each:
                    start the algorithm again for the subtree (1)
                c) all children have a NodeExecTime value → calculate execTime of parent 
                                (execTimeNode = elapTime - totalExecTimeChildren)

---

Note(1): While running the algorithm we append the node in our data structure with the associated execution time.
Note(2): Due to usage of integer/long values we have time values that are handled and displayed as 0ms, although they are between 0 - 1ms. Considering the occurring inaccuracies, the user should be informed about the amount of 0ms values.

**Comment by Florian-W** [comment] 2015-11-17 09:11
The implementation for calculating the execution time of a node was done in the RMNode class and works (by now), but is not in the origin branch yet.
The lookup for the most expensive subtransaction is done in the class UsecasePanel.
The button is implemented in the class RequestMetricsGui and works as it should, but could maybe be created in its own method.
There is a problem that an ActionListener (reacting on a click on the button) is added for every root case/ business transaction, that the user selects. So when the button is clicked, every registered ActionListener reacts, and the action handling is invoked not only for the currently selected transaction, but for all ever selected transactions.

A problem remains with the selection of the most expensive node. There's no "jump" to the entry in a table - it is only selected. And sometimes no row is selected, despite the most expensive node is calculated and is displayed as a subtransaction in our GUI.

**Comment by Florian-W** [comment] 2015-11-17 09:31
The selection problem (no node is selected) is caused by an incomplete lookup: only the direct children of the root node are checked for being the most expensive node. The other levels in our tree are not checked yet.

**Comment by Florian-W** [comment] 2015-11-17 11:15
The selection problem still remains. Although now all nodes are checked for being the right ones, a wrong node is sometimes selected.

For the ActionListener problem a workaround was found, which removes every ActionListener when the user selects a new transaction, and then adds an ActionListener for the current selection. Although it would be better to find a solution where the ActionListener is only registered for the current solution and removed again when the user changes the selection.

**Comment by nbrass** [comment] 2015-11-17 19:13
Solved all problems on this issue and closing it.

**Closed as completed by nbrass** 2015-11-17 19:13 UTC
Labels: enhancement, gui

**Comment by nbrass** [comment] 2015-11-17 21:01
Divided most expensive call button into 'Highest Execution Time' and 'Most Direct Children' buttons
